### ISSUE TITLE
Annotations not in response

### ISSUE THREAD

**Issue by Raudaschl** [karlicoss/pockexport#3]
Seems pocket no longer allows the annotations parameter to work blocking the export of highlights.

**Comment by karlicoss** [comment]
Hey, are you sure? Just checked my latest export (from last night) and it seems to contain `"annotations"` field. Did you follow the instructions [here](https://github.com/karlicoss/pockexport#setting-up)? You need to sniff the key with your browser devtools, 'regular' api keys don't export annotations.

**Comment by Raudaschl** [comment]
I see what happened. I used the consumer key from the app I registered with Pocket rather than from the web app request. Working fine now!
