### ISSUE TITLE
pocket.RateLimitException encountered

### ISSUE THREAD

**Issue by AB1908** [karlicoss/pockexport#6]
Sorry to bother you again but I ran into an error when setting this up. I obtained the access token using the instructions to the other repo that you had linked. I used that script to print it so I could copy it over. However, using it gives the following error:

    pocket.RateLimitException: User was authenticated, but access denied due to lack of permission or rate limiting. The provided keys do not have access to the requested API endpoint.

The full traceback is the following:

```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\pockexport\export.py", line 67, in <module>
    main()
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\pockexport\export.py", line 49, in main
    j = get_json(**params)
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\pockexport\export.py", line 39, in get_json
    return Exporter(**params).export_json()
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\pockexport\export.py", line 18, in export_json
    res = get(
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\pocket.py", line 57, in wrapped
    return self.make_request(url, payload)
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\pocket.py", line 154, in make_request
    return cls._make_request(url, payload, headers)
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\pocket.py", line 146, in _make_request
    raise EXCEPTIONS.get(r.status_code, PocketException)(
pocket.RateLimitException: User was authenticated, but access denied due to lack of permission or rate limiting. The provided keys do not have access to the requested API endpoint.
```

In my account settings, I do see that a new app has been connected
![image](https://user-images.githubusercontent.com/14124383/115708859-09b55a00-a360-11eb-99aa-7ffc6c9076b6.png)
but I fail to see how I can get it working. Any insight?

I would also appreciate it if you could delete the older version of this comment as it gives away personal info.

**Comment by karlicoss** [comment]
Hmm, sorry not sure, don't think I ever seen such an issue...
Curious, if you try the 'lawful good' way with creating a new app, does it work? Maybe it would help to debug.

And no worries, deleted the previous version!

**Comment by AB1908** [comment]
~~Unfortunately, that doesn't work either. Perhaps I'm doing something wrong.~~

They do work! I was using the wrong consumer key initially. However, I don't have my highlights. ☹️ 

I wonder if a consumer key mismatch is behind the previous error. Could you guide me through properly fetching my web consumer key just to be sure?

I also hit a unicode encoding problem. Here's the log:

```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\pockexport\export.py", line 67, in <module>
    main()
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\pockexport\export.py", line 51, in main
    dumper(js)
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\pockexport\exporthelpers\export_helper.py", line 63, in dump_to_stdout
    sys.stdout.write(data)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0142' in position 9380: character maps to <undefined>
```

This is probably a library error and I'll likely have to open an issue upstream. Any recommendations meanwhile to get around this issue or be able to use the highlight export method?

**Comment by AB1908** [comment]
So, I did find a way around this issue. I exported it to a file since 

https://github.com/karlicoss/exporthelpers/blob/9b9133ac407fa4ecc516e419120780f34d2cd5e6/export_helper.py#L62

doesn't encode to UTF-8 but 

https://github.com/karlicoss/exporthelpers/blob/9b9133ac407fa4ecc516e419120780f34d2cd5e6/export_helper.py#L65

does. I figured that I had to export to a file since you did have export path handling but it wasn't in the readme lol. I ended up figuring out how to use it from the `-h` flag which I was foolish enough to ignore. 

Reference: https://stackoverflow.com/questions/27092833/unicodeencodeerror-charmap-codec-cant-encode-characters

**Comment by karlicoss** [comment]
Re: utf-8 error. Hmm thanks, maybe it's some windows specific issue since I think Linux terminals can handle UTF-8 well? In fact the `encoding='utf-8'` in the second snippet was added by someone who was using Windows as well, it worked winthout it on OSX/Linux too. Don't know much details how it works behind the scenes.. maybe it guesses from the locale settings or something like that.
P.S. ah yes, your stackoverflow link kind of suggests the same. Although `PYTHONIOENCODING` isn't set for me on Linux, so there still must be some locale stuff going on

**Comment by AB1908** [comment]
Thanks for the explanation. I'm still trying to figure out what the problem is behind the other method. I wanted to integrate highlight exporting into my workflow and this seems like the best bet so far if I don't want to go through third party services. I suspect that a new access token is required every time I use the export. Does all this work fine on your end? If so, I'll probably give this a try through WSL. though that may be problematic since I won't have an X server running.

**Comment by karlicoss** [comment]
Re: auth issues -- did you manage to extract consumer key from the browser devtools? It should look similar to the consumer key that worked for you (from the app you registered), just a bit different.
I actually wonder if it's just public, you can find it on Github :D Maybe I should just hardcode it... https://github.com/veltzer/pyscrapers/blob/4586f55d0569b620924f42949dfaa2ebe5381bc6/pyscrapers/workers/getpocket.py#L17

After that, did you follow step 3? https://github.com/karlicoss/pockexport#setting-up You'll need a different access_token for a different consumer key, but once you got it it should work (I haven't had to renew mine since I set it up)

**Comment by AB1908** [comment]
OMG that does the trick! Thank you so much! I was using the wrong consumer key that I had extracted from https://getpocket.com/my-list since that's what https://app.pocket.com redirected to. I should have caught that sooner. You should probably put that consumer key in the readme.

**Comment by Silipwn** [comment]
Faced the same issue using the webapp method, got things working only after the intended way to get the `consumer_key`. i.e. applying via the developer portal. So no more highlights :(

**Comment by AB1908** [comment]
Hey, I did manage to extract my highlights. Maybe I could help?

**Comment by Silipwn** [comment]
Sure, would like to know more, did you use the above hard-coded key? Or any other procedure? 
I actually had setup this up sometime before. So, could potentially be some sort of deactivation as well.

**Comment by AB1908** [comment]
I used the hard coded key and used that to generate the access token. After that, everything worked out.

**Comment by Silipwn** [comment]
Yeah, this worked actually thanks a lot :)

**Comment by jordan8037310** [comment]
Can someone post the full revised steps? The documented readme steps don't do the job.

```
pocket.RateLimitException: User was authenticated, but access denied due to lack of permission or rate limiting. Invalid consumer key.
```

Nevermind -- my issue was grabbing the wrong key. 

Following up on this, the request to authorize the app still doesn't work with the correct `consumer_key`. I tried https://github.com/tapanpandita/pocket#oauth in order to get the access_token, but still get an error:

```
pocket.RateLimitException: User was authenticated, but access denied due to lack of permission or rate limiting. User rejected code.
```

**Comment by telotortium** [comment]
> Can someone post the full revised steps? The documented readme steps don't do the job.
> 
> ```
> pocket.RateLimitException: User was authenticated, but access denied due to lack of permission or rate limiting. Invalid consumer key.
> ```
> 
> Nevermind -- my issue was grabbing the wrong key.
> 
> Following up on this, the request to authorize the app still doesn't work with the correct `consumer_key`. I tried https://github.com/tapanpandita/pocket#oauth in order to get the access_token, but still get an error:
> 
> ```
> pocket.RateLimitException: User was authenticated, but access denied due to lack of permission or rate limiting. User rejected code.
> ```

@jordan8037310 Retrieving the key by opening up devtools on the Pocket web app didn't work for me. I had to use the hardcoded `consumer_key` mentioned in https://github.com/karlicoss/pockexport/issues/6#issuecomment-826580473

**Comment by AB1908** [comment]
@jordan8037310 sorry for not replying earlier! I missed this somehow.

**Comment by kingwiiwii** [comment]
`pocket.RateLimitException: User was authenticated, but access denied due to lack of permission or rate limiting. User rejected code.`

I get this regardless of what key I use. Is it safe to assume Pocket has closed this loophole ?
